apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: y6bpku3fw-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:d546f0990c37fc4fb410c9de4202a3ed3323376a@sha256:5011ad9e0fe7e2428d9675a6760dc6774c1f2eb2846f06e3f25f7b386ca4beaa
          name: container-image
